services:
  adcpython-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/adcpython-debug:${TAG}
    ports:
      - ${DEBUG_SSH_PORT}:${DEBUG_SSH_PORT}
      - ${DEBUG_PORT1}:${DEBUG_PORT1}

  adcpython:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/adcpython:${TAG}
