version: "2.4"
services:
  weston:
    image: torizon/weston-vivante:2
    environment:
      - ACCEPT_FSL_EULA=1
    # Required to get udev events from host udevd via netlink
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    cap_add:
      - CAP_SYS_TTY_CONFIG
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - "c 4:0 rmw"
      # ... for tty7
      - "c 4:7 rmw"
      # ... for /dev/input devices
      - "c 13:* rmw"
      - "c 199:* rmw"
      # ... for /dev/dri devices
      - "c 226:* rmw"

  DockerClone:
    depends_on:
      - weston
    devices: []
    image: torizonextras/uno-docker-clone
    command: ./project/DockerClone
    ports: []
    privileged: true
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
      - type: bind
        source: /dev/dri
        target: /dev/dri
      - type: bind
        source: /etc/os-release
        target: /etc/os-release
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    cap_add:
      - CAP_SYS_ADMIN
    shm_size: "256mb"
    device_cgroup_rules:
      # ... for /dev/dri devices
      - "c 226:* rmw"
