services:
  uartdotner-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/uartdotner-debug:${TAG}
    ports:
      - ${DEBUG_SSH_PORT}:${DEBUG_SSH_PORT}

  uartdotner:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/uartdotner:${TAG}
