services:
  uartdotnet-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/uartdotnet-debug:${TAG}
    ports:
      - ${DEBUG_SSH_PORT}:${DEBUG_SSH_PORT}
    devices:
      - /dev/colibri-uartc

  uartdotnet:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/uartdotnet:${TAG}
    devices:
      - /dev/colibri-uartc
