<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- Use the target framework that was used originally, e.g. netcoreapp3.1 -->
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <!-- Replace with the old package version that provided SerialPortDevice etc. -->
    <PackageReference Include="SharpGIS.NmeaParser" Version="2.0.0" />
    <PackageReference Include="System.IO.Ports" Version="7.0.0" />
  </ItemGroup>
</Project>
