services:
  adcc-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/adcc-debug:${TAG}
    ports:
      - ${DEBUG_SSH_PORT}:${DEBUG_SSH_PORT}

  adcc:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/adcc:${TAG}
